### ISSUE TITLE
Change lib name ?

### ISSUE THREAD

**Issue by fabienjuif** [Trampss/trampss-redux-factory#18]
From @bpetetot 

> The librairy name doesn't speak itself... and is very long.
> Does it be better to call it with factory in the lib name, like : redux-factory or trampss-redux-factory ?

**Comment by fabienjuif** [comment]
@guillaumecrespel what about `trampss-redux-factory` then ?

**Comment by guillaumecrespel** [comment]
redux-factory is already use
