### ISSUE TITLE
getBy -> filterBy

### ISSUE THREAD

**Issue by fabienjuif** [Trampss/trampss-redux-factory#42]

**Comment by fabienjuif** [comment]
@bpetetot
@delphinemillet 
@guillaumecrespel 

Can you vote for this proposition ?
Do you see the profit ?

**Comment by guillaumecrespel** [comment]
Just `filter`, is not an option ?

1) filterBy()
2) filter()

**Comment by fabienjuif** [comment]
Since we understand the purpose of `getBy` by its name, we don't need to rename the selector.
If you want to argue feel free to reopen an issue
