### ISSUE TITLE
change type names (uniq/map)

### ISSUE THREAD

**Issue by fabienjuif** [Trampss/trampss-redux-factory#45]
#44

**Comment by fabienjuif** [comment]
Proposition from coworkers : 
 - keyValue
 - simpleObject

**Comment by bpetetot** [comment]
I would have named them : 
- `array` (for map)
- `object` (for uniq)

**Comment by fabienjuif** [comment]
- I don't like `array` because this is not an array (this is a map, with an array) => Maybe we'll add a simple `array` reducer sometimes
 - I like `object` but I'm afraid of possibles bugs with `Object` it could generates for beginers

**Comment by fabienjuif** [comment]
Names are : 
 - keyValue
 - simpleObject
