### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by fabienjuif** [Trampss/trampss-redux-factory#47]
Write to the README that the lib handle the immutability

**Comment by bpetetot** [comment]
Rewrite the following line : https://github.com/Trampss/trampss-redux-factory/blame/master/README.md#L195

**signature is the following :**
`mapPayload(<regex>)(<mapper(payload)>)`

**change the description :**
> create middleware and map the payload of the corresponding redux actions type by the regex

**Comment by bpetetot** [comment]
Rewrite the following line : https://github.com/Trampss/trampss-redux-factory/blame/master/README.md#L218

**Bad signature :**
```es6
export default factory({ pre: [mapPayload(/SET_TODOS/)(mapper)] })('id')('api.raw')('todos')
```

**Correct signature :**
```es6
export default factory({ pre: [mapPayload(/SET_TODOS/)(mapper)] })({ key: 'id', path: 'api.raw', name: 'todos' })
```
