### ISSUE TITLE
Middlewares configuration / pre -> before / post -> after

### ISSUE THREAD

**Issue by fabienjuif** [Trampss/trampss-redux-factory#50]
This is a @bpetetot question.

👍 if you agree
👎 if you disagree

**Comment by guillaumecrespel** [comment]
:muscle: @bpetetot

**Comment by fabienjuif** [comment]
@guillaumecrespel 
@bpetetot

Can you argue a little about this choice ?
I don't really mind, I would like not to change signature every week if this is not for a good reason :)

**Comment by fabienjuif** [comment]
We find both names in others libs.
Mongoose for instance use pre and post.

I prefers avoiding renames every weeks.
